import Head from 'next/head'
import styles from '../styles/Home.module.css'
import img from '../public/images/backToSchool.png'
import HomeCard from '../components/HomeCard'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Clothing Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
         <HomeCard />
      </div>
    </div>
  )
}
